name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Update to a version that supports the syntax

      - name: Install dependencies
        run: npm install

      - name: Build and deploy to GitHub Pages (Staging)
        if: github.ref == 'refs/heads/staging'
        run: |
          npm run build
          echo "/* /gh-pages-staging/index.html 200" > build/vite.config.js
          npx gh-pages -d build -b gh-pages-staging -u "${{ secrets.TOKEN }}"

      - name: Build and deploy to GitHub Pages (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          npm run build
          echo "/* /gh-pages-production/index.html 200" > build/vite.config.js
          npx gh-pages -d build -b gh-pages-production -u "${{ secrets.TOKEN }}"
